In [5]:
import numpy as np
from jiraone import echo

# 1D array
a1D = np.array([1, 2, 3, 4])
# 2D array
a2D = np.array([[1, 2], [3, 4]])
# 3D array
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
echo(a1D)
echo(a2D)
echo(a3D)
# using dtype when assigning types in array
# the below will produce an error because it is outside the range
assign_type = np.array([127, 128, 129], dtype=np.int8)


array([1, 2, 3, 4])
array([[1, 2],
       [3, 4]])
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])


An 8-bit signed integer represents integers from -128 to 127.
Assigning the int8 array to integers outside of this range results in overflow.


In [6]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


Notice when you perform operations with two arrays of the same `dtype`: `uint32`, the resulting array is the same type. When you perform operations with different dtype, NumPy will assign a new type that satisfies all of the array elements involved in the computation, here `uint32` and `int32` can both be represented in as `int64`.

In [7]:
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


### Creating 1D array functions
- `numpy.arange` creates arrays with regularly incrementing values

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Note: best practice for `numpy.arange` is to use integer start, end, and step values

- `numpy.linspace` will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [12]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

The advantage of this creation function is that you guarantee the number of elements and the starting and end point. The previous `arange(start, stop, step)` will not include the value `stop`.