## Arrays
NumPy arrays can be defined using Python sequences such as lists and tuples. Lists and tuples are defined using `[...]` and `(...)`, respectively. Lists and tuples can define ndarray creation:
- a list of numbers will create a 1D array,
- a list of lists will create a 2D array,
- further nested lists will create higher-dimensional arrays. In general, any array object is called an ndarray in NumPy.

In [5]:
import numpy as np
from jiraone import echo

# 1D array
a1D = np.array([1, 2, 3, 4])
# 2D array
a2D = np.array([[1, 2], [3, 4]])
# 3D array
a3D = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
echo(a1D)
echo(a2D)
echo(a3D)
# using dtype when assigning types in array
# the below will produce an error because it is outside the range
assign_type = np.array([127, 128, 129], dtype=np.int8)


array([1, 2, 3, 4])
array([[1, 2],
       [3, 4]])
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])


An 8-bit signed integer represents integers from -128 to 127.
Assigning the int8 array to integers outside of this range results in overflow.


In [6]:
a = np.array([2, 3, 4], dtype=np.uint32)
b = np.array([5, 6, 7], dtype=np.uint32)
c_unsigned32 = a - b
print('unsigned c:', c_unsigned32, c_unsigned32.dtype)

unsigned c: [4294967293 4294967293 4294967293] uint32


Notice when you perform operations with two arrays of the same `dtype`: `uint32`, the resulting array is the same type. When you perform operations with different dtype, NumPy will assign a new type that satisfies all of the array elements involved in the computation, here `uint32` and `int32` can both be represented in as `int64`.

In [7]:
c_signed32 = a - b.astype(np.int32)
print('signed c:', c_signed32, c_signed32.dtype)

signed c: [-3 -3 -3] int64


### Creating 1D array functions
- `numpy.arange` creates arrays with regularly incrementing values

In [8]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [11]:
np.arange(2, 3, 0.1)

array([2. , 2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9])

Note: best practice for `numpy.arange` is to use integer start, end, and step values

- `numpy.linspace` will create arrays with a specified number of elements, and spaced equally between the specified beginning and end values

In [12]:
np.linspace(1., 4., 6)

array([1. , 1.6, 2.2, 2.8, 3.4, 4. ])

The advantage of this creation function is that you guarantee the number of elements and the starting and end point. The previous `arange(start, stop, step)` will not include the value `stop`.

### Creating 2D array
- The 2D array creation functions e.g. `numpy.eye`, `numpy.diag`, and `numpy.vander` define properties of special matrices represented as 2D arrays.

In [16]:
p = np.eye(3)
print(p)
print("*" * 10)
k = np.eye(3, 5)
print(k)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
**********
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


`numpy.diag` can define either a square 2D array with given values along the diagonal or if given a 2D array returns a 1D array that is only the diagonal elements

In [17]:
k = np.diag([1, 2, 3])
print(k)
print("*" * 10)
s = np.diag([1,2,3], 1)
print(s)

[[1 0 0]
 [0 2 0]
 [0 0 3]]
**********
[[0 1 0 0]
 [0 0 2 0]
 [0 0 0 3]
 [0 0 0 0]]


`vander(x, n)` defines a Vandermonde matrix as a 2D NumPy array. Each column of the Vandermonde matrix is a decreasing power of the input 1D array or list or tuple, `x` where the highest polynomial order is `n-1`.

In [19]:
p = np.vander(np.linspace(0, 2, 5), 2)
print(p)

[[0.  1. ]
 [0.5 1. ]
 [1.  1. ]
 [1.5 1. ]
 [2.  1. ]]


### 3D array
- The ndarray creation functions e.g. `numpy.ones`, `numpy.zeros`, and `random` define arrays based upon the desired shape. `numpy.zeros` will create an array filled with 0 values with the specified shape

In [22]:
p = np.zeros((2, 3))
print(p)
print("-" * 20)
c = np.zeros((2, 3, 2))
print(c)

[[0. 0. 0.]
 [0. 0. 0.]]
--------------------
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


`numpy.ones` will create an array filled with 1 values. It is identical to `zeros` in all other respects as such:

In [25]:
p = np.ones((2, 3))
print(p)
print("-" * 20)
k = np.ones((2, 3, 2))
print(k)

[[1. 1. 1.]
 [1. 1. 1.]]
--------------------
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


The `random` method of the result of `default_rng` will create an array filled with random values between 0 and 1. It is included with the `numpy.random` library

In [26]:
from numpy.random import default_rng

g = default_rng(42).random((2, 3))
print(g)
print("-" * 20)
f = default_rng(42).random((2, 3, 2))
print(f)

[[0.77395605 0.43887844 0.85859792]
 [0.69736803 0.09417735 0.97562235]]
--------------------
[[[0.77395605 0.43887844]
  [0.85859792 0.69736803]
  [0.09417735 0.97562235]]

 [[0.7611397  0.78606431]
  [0.12811363 0.45038594]
  [0.37079802 0.92676499]]]


`numpy.indices` will create a set of arrays (stacked as a one-higher dimensioned array), one per dimension with each representing variation in that dimension

In [27]:
r = np.indices((3,3))
print(r)

[[[0 0 0]
  [1 1 1]
  [2 2 2]]

 [[0 1 2]
  [0 1 2]
  [0 1 2]]]


### Replicate, join or mutate arrays
- When you assign an array or its elements to a new variable, you have to explicitly `numpy.copy` the array, otherwise the variable is a view into the original array.

In [28]:
a = np.array([1, 2, 3, 4, 5, 6])
b = a[:2]
b += 1
print("a =", a, "; b =", b)

a = [2 3 3 4 5 6] ; b = [2 3]


When you added 1 to `b` you would get the same result by adding 1 to `a[:2]`. If you want to create a new array, use the `numpy.copy` array creation routine

In [29]:
a = np.array([1, 2, 3, 4])
b = a[:2].copy()
b += 1
print("a =", a, "; b =", b)

a = [1 2 3 4] ; b = [2 3]


There are a number of routines to join existing arrays e.g. `numpy.vstack`, `numpy.hstack`, and `numpy.block`. Here is an example of joining four 2-by-2 arrays into a 4-by-4 array using `block`

In [30]:
A = np.ones((2, 2))
B = np.eye(2, 2)
C = np.zeros((2, 2))
D = np.diag((-3, -4))
E = np.block([[A, B], [C, D]])
print(E)

[[ 1.  1.  1.  0.]
 [ 1.  1.  0.  1.]
 [ 0.  0. -3.  0.]
 [ 0.  0.  0. -4.]]


### Reading arrays from disk, either from standard or custom formats
This is the most common case of large array creation. The details depend greatly on the format of data on disk

#### Standard binary formats
Various fields have standard formats for array data. The following lists the ones with known Python libraries to read them and return NumPy arrays

```text
HDF5: h5py
FITS: Astropy
```
Examples of formats that cannot be read directly but for which it is not hard to convert are those formats supported by libraries like PIL

#### Common ASCII formats
Delimited files such as comma separated value (csv) and tab separated value (tsv) files are used for programs like Excel and LabView. Python functions can read and parse these files line-by-line. NumPy has two standard routines for importing a file with delimited data `numpy.loadtxt` and `numpy.genfromtxt`

```shell
$ cat simple.csv
x, y
0, 0
1, 1
2, 4
3, 9
```
importing `simple.csv` using `numpy.loadtxt`


In [ ]:
c = np.loadtxt('simple.csv', delimiter=',' , skiprows=1)

More generic ASCII files can be read using `scipy.io` and `Pandas`.

#### Creating arrays from raw bytes through the use of strings or buffers
There are a variety of approaches one can use. If the file has a relatively simple format then one can write a simple I/O library and use the NumPy `fromfile()` function and `.tofile()` method to read and write NumPy arrays directly (mind your byteorder though!)

#### Use of special library functions (e.g. SciPy, pandas, and OpenCV)
NumPy is the fundamental library for array containers in the Python Scientific Computing stack. Many Python libraries, including SciPy, Pandas, and OpenCV, use NumPy ndarrays as the common format for data exchange
