## Data types
NumPy supports a much greater variety of numerical types than Python does. This section shows which are available, and how to modify an array’s data-type.

### Array types and conversions between types


In [1]:
import numpy as np
z = np.arange(3, dtype=np.uint8)
print(z)

[0 1 2]


Array types can also be referred to by character codes, for example:

In [2]:
x = np.array([1, 2, 3], dtype='f')
print(x)
print("-" * 20)
y = np.array([1, 2, 3], dtype='d')
print(y)

[1. 2. 3.]
--------------------
[1. 2. 3.]


Note that, above, we could have used the Python float object as a dtype instead of `numpy.float64`. NumPy knows that int refers to `numpy.int_`, bool means `numpy.bool`, that float is `numpy.float64` and complex is `numpy.complex128`. The other data-types do not have Python equivalents.

In [5]:
print(z.dtype)
print("-" * 20)
d = np.dtype(np.int64)
print(d)
print("-" * 20)
x = np.issubdtype(d, np.integer)
print(x)

uint8
--------------------
int64
--------------------
True


### Numerical Data Types
There are 5 basic numerical types representing booleans (`bool`), integers (`int`), unsigned integers (`uint`) floating point (`float`) and `complex`. A basic numerical type name combined with a numeric bitsize defines a concrete type. For example, `numpy.float64` is a 64 bit floating point data type. Some types, such as `numpy.int_` and `numpy.intp`, have differing bitsizes, dependent on the platforms (e.g. 32-bit vs. 64-bit CPU architectures).

### Data Types for Strings and Bytes
In addition to numerical types, NumPy also supports storing unicode strings, via the `numpy.str_` dtype (U character code), null-terminated byte sequences via `numpy.bytes_` (S character code), and arbitrary byte sequences, via `numpy.void` (V character code).

In [ ]:
x = np.array(["hello", "world!"])
print(x)

Here the data type is detected as a unicode string that is a maximum of 6 code points long, enough to store both entries without truncation

In [6]:
x = np.array(["hello", "world!"], dtype="U5")
print(x)
y = np.array(["hello", "world!"], dtype="U7")
print(y)

['hello' 'world']
['hello' 'world!']


We can see the zero-padding a little more clearly if we use the bytes data type and ask NumPy to print out the bytes in the array buffer:

In [7]:
x = np.array(["hello", "world"], dtype="S7").tobytes()
print(x)

b'hello\x00\x00world\x00\x00'


Each entry is padded with two extra null bytes. Note however that NumPy cannot tell the difference between intentionally stored trailing nulls and padding nulls:

In [8]:
x = [b"hello\0\0", b"world"]
a = np.array(x, dtype="S7")
print(a[0])
print("-" * 20)
c = a[0] == x[0]
print(c)

b'hello'
--------------------
False
